# Generated by Django 3.2.5 on 2021-08-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=1024)),
                ('test', models.CharField(max_length=1024)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Productspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=1024)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Rawcomponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('grade', models.CharField(max_length=1024)),
                ('main_component', models.BooleanField(default=True)),
                ('material', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Productrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.process')),
                ('raw_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.rawcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=1024, verbose_name='Product Name')),
                ('billed_name', models.CharField(max_length=1024, verbose_name='Billed Name')),
                ('cost', models.FloatField(blank=True)),
                ('IGST', models.FloatField(blank=True)),
                ('SGST', models.FloatField()),
                ('CGST', models.FloatField()),
                ('code', models.CharField(max_length=200, unique=True)),
                ('job_name', models.CharField(max_length=1024)),
                ('main_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.rawcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Processcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.TimeField()),
                ('type_of_tools', models.CharField(choices=[('t', 'Tools'), ('i', 'Instrunmental')], default='Tools', max_length=1024)),
                ('process_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.process')),
            ],
        ),
    ]
