# Generated by Django 3.2.5 on 2021-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processcost',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processcost',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrequirements',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productrequirements',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspec',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawcomponent',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rawcomponent',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supliers_contact_details',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supliers_contact_details',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
