# Generated by Django 3.2.5 on 2021-08-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('address_line1', models.CharField(max_length=1024, null=True)),
                ('address_line2', models.CharField(max_length=1024, null=True)),
                ('address_line3', models.CharField(max_length=1024, null=True)),
                ('office_email', models.CharField(blank=True, max_length=1024, null=True)),
                ('office_pnone_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('acc_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=1024, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('purchase_company', models.BooleanField(default=True)),
                ('ratings', models.IntegerField(null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='supliers_contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024, null=True)),
                ('phone_no', models.CharField(max_length=1024, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('post', models.CharField(max_length=1024, null=True)),
                ('company_details', models.ForeignKey(blank=True, db_column='company_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='master.company_details')),
            ],
        ),
    ]
