# Generated by Django 3.2.7 on 2021-11-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_product_price_tenant_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
