# Generated by Django 3.2.7 on 2021-11-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_delete_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequirements',
            name='product',
        ),
        migrations.AddField(
            model_name='productrequirements',
            name='product_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.product_price'),
            preserve_default=False,
        ),
    ]
