# Generated by Django 3.2.7 on 2021-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20211112_1542'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='company_details',
        #     name='vendor_code',
        #     field=models.CharField(default=11, max_length=1024, unique=True),
        #     preserve_default=False,
        # ),
    ]
