# Generated by Django 3.2.7 on 2021-11-20 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_company_details_vendor_code'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='CGST',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='IGST',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='SGST',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='cost',
        # ),
        # migrations.AddField(
        #     model_name='product_price',
        #     name='CGST',
        #     field=models.FloatField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='product_price',
            name='IGST',
            field=models.FloatField(blank=True, default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_price',
            name='SGST',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
