# Generated by Django 3.2.7 on 2021-11-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20211120_1103'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product_price',
        #     name='CGST',
        # ),
        # migrations.AlterField(
        #     model_name='company_details',
        #     name='vendor_code',
        #     field=models.CharField(default=10, max_length=224, unique=True),
        #     preserve_default=False,
        # ),
    ]
