# Generated by Django 3.2.7 on 2021-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20211120_1106'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product_price',
        #     name='CGST',
        #     field=models.FloatField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='product_price',
        #     name='SGST',
        #     field=models.FloatField(null=True),
        # ),
    ]
