# Generated by Django 3.2.7 on 2021-11-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20211120_1107'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product_price',
        #     name='CGST',
        # ),
    ]
