# Generated by Django 3.2.7 on 2021-11-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_remove_product_price_cgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_price',
            name='CGST',
            field=models.FloatField(null=True),
        ),
    ]
