# Generated by Django 3.2.7 on 2021-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_product_price_cgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CGST',
        ),
        migrations.RemoveField(
            model_name='product',
            name='IGST',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SGST',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AlterField(
            model_name='company_details',
            name='vendor_code',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='SGST',
            field=models.FloatField(null=True),
        ),
    ]
