# Generated by Django 3.2.7 on 2021-11-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20211120_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='vendor_code',
        ),
    ]
