# Generated by Django 3.2.7 on 2021-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_company_details_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
