# Generated by Django 3.2.7 on 2021-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_product_unit'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='company_details',
        #     name='vendor_code',
        #     field=models.CharField(max_length=224, unique=True),
        # ),
    ]
