# Generated by Django 3.2.7 on 2021-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_company_details_vendor_code'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='company_details',
        #     name='vendor_code',
        #     field=models.CharField(default='12', max_length=224, unique=True),
        # ),
    ]
