# Generated by Django 3.2.7 on 2021-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_alter_company_details_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='vendor_code',
            field=models.CharField(max_length=224),
        ),
    ]
