# Generated by Django 3.2.7 on 2021-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_remove_company_details_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='vendor_code',
            field=models.CharField(default=10, max_length=224),
            preserve_default=False,
        ),
    ]
