# Generated by Django 3.2.7 on 2021-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_company_details_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='CGST',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='IGST',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='SGST',
            field=models.FloatField(default=0),
        ),
    ]
