# Generated by Django 3.2.7 on 2021-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_auto_20211122_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processcost',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productrequirements',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rawcomponent',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supliers_contact_details',
            name='tenant_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
