# Generated by Django 3.2.7 on 2021-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_auto_20211127_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
