# Generated by Django 3.2.7 on 2021-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_alter_productrequirements_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcomponent',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
