# Generated by Django 3.2.7 on 2021-12-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_rawcomponent_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='worker_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
