# Generated by Django 3.2.7 on 2021-10-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='cutting_stock',
        ),
        migrations.RenameModel(
            old_name='Stock_History',
            new_name='cutting_stock_history',
        ),
    ]
