# Generated by Django 3.2.5 on 2021-09-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.SmallIntegerField()),
                ('dispatch_number', models.PositiveIntegerField()),
                ('inward_date', models.DateTimeField(auto_now=True)),
                ('dispatch_worker', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.FloatField()),
                ('qty', models.FloatField()),
                ('bal_qty', models.FloatField()),
                ('error_qty', models.FloatField()),
                ('dc_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatch_details')),
            ],
        ),
    ]
