# Generated by Django 3.2.5 on 2021-09-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('company_id', models.SmallIntegerField()),
                ('dispatch_number', models.PositiveIntegerField(unique=True)),
                ('dispatch_date', models.DateTimeField(auto_now=True)),
                ('dispatch_worker', models.CharField(max_length=1024, null=True)),
                ('financial_period', models.DateField(auto_now=True)),
            ],
        ),
    ]
