# Generated by Django 3.2.5 on 2021-09-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch_materials',
            old_name='dc_details',
            new_name='dispatch_details',
        ),
    ]
