# Generated by Django 3.2.5 on 2021-09-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_rename_dc_details_dispatch_materials_dispatch_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch_details',
            old_name='inward_date',
            new_name='dispatch_date',
        ),
    ]
