# Generated by Django 3.2.5 on 2021-09-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_alter_dispatch_details_dispatch_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_details',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dispatch_materials',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
    ]
