# Generated by Django 3.2.5 on 2021-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_auto_20210908_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch_materials',
            name='item',
        ),
        migrations.AddField(
            model_name='dispatch_materials',
            name='product_details',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
