# Generated by Django 3.2.7 on 2021-11-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_dispatch_materials_quality_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch_details',
            name='company_id',
        ),
    ]
