# Generated by Django 3.2.7 on 2021-11-11 11:46

import dispatch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_remove_dispatch_details_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_details',
            name='dispatch_number',
            field=models.PositiveIntegerField(default=dispatch.models.dispatch_num),
        ),
    ]
