# Generated by Django 3.2.7 on 2021-11-11 12:05

import dispatch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_alter_dispatch_details_dispatch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_details',
            name='dispatch_number',
            field=models.CharField(default=dispatch.models.dispatch_num, max_length=1024, null=True),
        ),
    ]
