# Generated by Django 3.2.7 on 2021-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_alter_dispatch_details_dispatch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_details',
            name='company_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
