# Generated by Django 3.2.7 on 2021-11-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_dispatch_details_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_details',
            name='dispatch_date',
            field=models.DateField(auto_now=True),
        ),
    ]
