# Generated by Django 3.2.7 on 2021-11-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_alter_dispatch_details_dispatch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch_details',
            name='company_id',
        ),
    ]
