# Generated by Django 3.2.7 on 2021-11-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_remove_dispatch_details_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_materials',
            name='dispatch_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='dispatch.dispatch_details'),
        ),
    ]
