# Generated by Django 3.2.5 on 2021-08-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
