# Generated by Django 3.2.7 on 2021-09-23 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outward_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('dc_number', models.IntegerField(unique=True)),
                ('dc_date', models.DateField(auto_now=True)),
                ('vehicle_number', models.CharField(max_length=1054)),
                ('financial_period', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='outward_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('financial_period', models.DateField(auto_now=True)),
                ('product', models.PositiveIntegerField()),
                ('qty', models.FloatField()),
                ('bal_qty', models.FloatField()),
                ('outward_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outward.outward_details')),
            ],
        ),
    ]
