# Generated by Django 3.2.5 on 2021-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_register_staus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='staus',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
