# Generated by Django 3.2.5 on 2021-09-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_register_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='staus',
            new_name='status',
        ),
    ]
