# Generated by Django 3.2.7 on 2021-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_rename_staus_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='domain',
            field=models.CharField(default='xyz', max_length=1024),
            preserve_default=False,
        ),
    ]
