# Generated by Django 3.2.5 on 2021-09-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('company', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('accepted', models.BooleanField(default=True)),
            ],
        ),
    ]
