# Generated by Django 3.2.5 on 2021-09-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_stock_history_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_history',
            name='tenant_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
