# Generated by Django 3.2.5 on 2021-08-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210824_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_history',
            old_name='stock_table',
            new_name='stock_id',
        ),
    ]
