# Generated by Django 3.2.5 on 2021-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_stock_table_stock_history_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_history',
            name='after_process',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_history',
            name='change_in_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_history',
            name='instock_qty',
            field=models.FloatField(),
        ),
    ]
