# Generated by Django 3.2.5 on 2021-09-01 16:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210901_0719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock_history',
            managers=[
                ('year', django.db.models.manager.Manager()),
            ],
        ),
    ]
