# Generated by Django 3.2.5 on 2021-08-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dc_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.SmallIntegerField()),
                ('dc_number', models.PositiveIntegerField()),
                ('dc_date', models.DateField()),
                ('inward_date', models.DateTimeField(auto_now=True)),
                ('inward_worker', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Dc_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('bal_qty', models.PositiveIntegerField()),
                ('error_qty', models.IntegerField()),
                ('dc_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inward.dc_details')),
            ],
        ),
    ]
