# Generated by Django 3.2.5 on 2021-08-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1024)),
                ('materials', models.CharField(max_length=1024)),
                ('no_of_items', models.PositiveIntegerField()),
                ('rem_items', models.PositiveIntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
