# Generated by Django 3.2.5 on 2021-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_materials',
            name='bal_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dc_materials',
            name='error_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dc_materials',
            name='item',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dc_materials',
            name='qty',
            field=models.FloatField(),
        ),
    ]
