# Generated by Django 3.2.5 on 2021-09-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0002_auto_20210901_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_details',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
    ]
