# Generated by Django 3.2.5 on 2021-09-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0003_dc_details_financial_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_materials',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
    ]
