# Generated by Django 3.2.7 on 2021-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0006_auto_20210908_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_details',
            name='tenant_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
