# Generated by Django 3.2.7 on 2021-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0009_remove_dc_materials_quality_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_details',
            name='dc_number',
            field=models.CharField(max_length=1024),
        ),
    ]
