# Generated by Django 3.2.7 on 2021-09-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocess',
            name='prod_name_price',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
