# Generated by Django 3.2.7 on 2021-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processcard', '0002_subprocess_prod_name_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Production',
            new_name='Production_card',
        ),
        migrations.RenameField(
            model_name='subprocess',
            old_name='prod_name_price',
            new_name='product_price',
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='process_name',
            field=models.CharField(max_length=1054),
        ),
    ]
