# Generated by Django 3.2.7 on 2021-11-20 04:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('processcard', '0004_auto_20211119_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainprocess',
            name='process_name',
        ),
        migrations.RemoveField(
            model_name='mainprocess',
            name='stage',
        ),
        migrations.AddField(
            model_name='mainprocess',
            name='title',
            field=models.CharField(default='main', max_length=1024),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='process_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=1024)),
                ('test', models.CharField(max_length=1024)),
                ('cost', models.FloatField()),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='processcard.process_name')),
            ],
            options={
                'verbose_name_plural': 'processdetails',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='mainprocess',
            name='process_details',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processcard.process_name'),
        ),
    ]
