# Generated by Django 3.2.7 on 2021-11-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_process',
            old_name='stage',
            new_name='process',
        ),
        migrations.RemoveField(
            model_name='sub_process',
            name='process_name',
        ),
        migrations.AddField(
            model_name='sub_process',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_process',
            name='product_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
