# Generated by Django 3.2.5 on 2021-09-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210915_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='tenant_company',
        #     field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_company', to='authentication.tenant_company'),
        #     preserve_default=False,
        # ),
    ]
