# Generated by Django 3.2.5 on 2021-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1024)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='domain',
        ),
    ]
