# Generated by Django 3.2.7 on 2021-10-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210915_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_company', to='authentication.tenant_company'),
            preserve_default=False,
        ),
    ]
