# Generated by Django 3.2.5 on 2021-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_tenant_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_company',
            name='joined_data',
            field=models.DateField(auto_now=True),
        ),
    ]
