# Generated by Django 3.2.5 on 2021-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_tenant_company_joined_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(default='domain', max_length=1024),
            preserve_default=False,
        ),
    ]
