# Generated by Django 3.2.5 on 2021-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain',
        ),
        migrations.AddField(
            model_name='tenant_company',
            name='domain',
            field=models.CharField(default='dd', max_length=1024),
            preserve_default=False,
        ),
    ]
