# Generated by Django 3.2.7 on 2021-10-28 03:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_menu'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='menu',
        #     options={'verbose_name_plural': 'menus'},
        # ),
        # migrations.RenameField(
        #     model_name='menu',
        #     old_name='menu',
        #     new_name='menu_name',
        # ),
        migrations.AddField(
            model_name='emp_roles',
            name='tenant_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant_company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant_company'),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='employee_name',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='level',
        #     field=models.PositiveIntegerField(default=1, editable=False),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='lft',
        #     field=models.PositiveIntegerField(default=1, editable=False),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='parent',
        #     field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authentication.menu'),
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='rght',
        #     field=models.PositiveIntegerField(default=1, editable=False),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='slug',
        #     field=models.SlugField(default=1, unique=True),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='tenant_company',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant_company'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='menu',
        #     name='tree_id',
        #     field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='menu',
        #     name='url',
        #     field=models.URLField(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='menu',
        #     unique_together={('parent', 'slug')},
        # ),
    ]
