# Generated by Django 3.2.5 on 2021-09-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210910_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_company',
            name='city',
            field=models.CharField(max_length=1024),
        ),
    ]
