# Generated by Django 3.2.7 on 2021-11-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20211028_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
