# Generated by Django 3.2.7 on 2021-11-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delete_menu'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='tenant_company',
        #     name='domain',
        #     field=models.CharField(max_length=1004, unique=True),
        # ),
    ]
