# Generated by Django 3.2.7 on 2021-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_tenant_company_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_company',
            name='domain',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
