# Generated by Django 3.2.7 on 2021-11-19 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_tenant_company_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.BooleanField(default=False)),
                ('inward', models.BooleanField(default=False)),
                ('dispatch', models.BooleanField(default=False)),
                ('production', models.BooleanField(default=False)),
                ('billing', models.BooleanField(default=False)),
                ('quality', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
