# Generated by Django 3.2.7 on 2021-11-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20211122_1521'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='menu_tab',
        #     name='menu_link',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_link', to='authentication.menu_link'),
        # ),
    ]
