# Generated by Django 3.2.7 on 2021-11-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_menu_tab_menu_link'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='menu_tab',
        #     name='menu_link',
        # ),
    ]
