# Generated by Django 3.2.7 on 2021-11-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20211122_1524'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='menu_tab',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='menu_tab',
        #     name='menu_link',
        # ),
        # migrations.RemoveField(
        #     model_name='menu_tab',
        #     name='parent',
        # ),
        # migrations.RemoveField(
        #     model_name='menu_tab',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='menu_link',
        # ),
        # migrations.DeleteModel(
        #     name='menu_tab',
        # ),
    ]
