# Generated by Django 3.2.7 on 2021-11-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20211122_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'mainprocess',
            },
        ),
        migrations.RenameModel(
            old_name='menu_link',
            new_name='menu_link_url',
        ),
        migrations.DeleteModel(
            name='menu_tab',
        ),
        migrations.AddField(
            model_name='menu_list',
            name='menu_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_link', to='authentication.menu_link_url'),
        ),
        migrations.AddField(
            model_name='menu_list',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authentication.menu_list'),
        ),
        migrations.AddField(
            model_name='menu_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='menu_list',
            unique_together={('parent', 'slug')},
        ),
    ]
