# Generated by Django 3.2.7 on 2021-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_rename_process_production_sub_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocess',
            name='prod_name_price',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
