# Generated by Django 3.2.7 on 2021-09-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_subprocess_prod_name_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Production',
            new_name='Production_card',
        ),
        migrations.RenameField(
            model_name='subprocess',
            old_name='prod_name_price',
            new_name='product_price',
        ),
    ]
