# Generated by Django 3.2.7 on 2021-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20210928_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocess',
            name='process_name',
            field=models.CharField(max_length=1054),
        ),
    ]
