# Generated by Django 3.2.7 on 2021-10-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semi_product_price',
            old_name='semi_product',
            new_name='semi_product_details',
        ),
        migrations.AlterField(
            model_name='cutting_details',
            name='cutting_number',
            field=models.PositiveIntegerField(),
        ),
    ]
