# Generated by Django 3.2.7 on 2021-10-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0003_alter_cutting_details_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawcomponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('rname', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('grade', models.CharField(max_length=1024)),
                ('main_component', models.BooleanField(default=True)),
                ('material', models.CharField(max_length=1024)),
                ('financial_period', models.DateField(auto_now=True)),
                ('worker_name', models.CharField(max_length=1024)),
            ],
        ),
    ]
