# Generated by Django 3.2.7 on 2021-10-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0004_rawcomponent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rawcomponent',
            new_name='semi_raw_component',
        ),
    ]
