# Generated by Django 3.2.7 on 2021-10-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0005_rename_rawcomponent_semi_raw_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='semi_product_price',
            name='quanity',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semi_product',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rod.semi_raw_component'),
        ),
    ]
