# Generated by Django 3.2.7 on 2021-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0006_auto_20211001_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semi_product_price',
            name='quanity',
        ),
        migrations.AddField(
            model_name='semi_product',
            name='quanity',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
