# Generated by Django 3.2.7 on 2021-10-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0007_auto_20211001_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semi_product',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
